version: '2'
services:
  libregob:
    image: fabricadesoftwarelibre/libregob:18.1
    networks:
      - libregob-network
    depends_on:
      - libregobdb
    ports:
        # Colocamos LibreGOB en el puerto 80 para acceso general.
      - "80:8069"
        # Publicamos el puerto de longpolling.
      - "8072:8072"
    volumes:
        # Reemplazar con la ruta en el servidor.
        # Ruta hacia los addons privados.
      - ~/libregob/mnt/extra-addons:/mnt/extra-addons/:z
        # Ruta hacia el filestore.
      - ~/libregob/var/lib/odoo:/var/lib/odoo/:z
        # Ruta al directorio de configuraciones.
      - ~/libregob/etc/odoo:/etc/odoo/:z
    environment:
      # Deben ser las mismas que en db.
      - HOST=libregobdb # default db
      - PORT=5432 # default 5432
      - USER=libregob
      - PASSWORD=libregobpwd
    # impide el acceso a la lista de bases: --no-database-list
    command: -- --no-database-list
  libregobdb:
    image: postgres:9.4
    volumes:
        # Reemplazar con la ruta en el servidor.
        # Ruta hacia el almacenamiento de postgresql.
      - ~/libregobdb/var/lib/postgresql/data:/var/lib/postgresql/data/:z
    networks:
      - libregob-network
    environment:
      - POSTGRES_USER=libregob
      - POSTGRES_PASSWORD=libregobpwd
networks:
  libregob-network:
